#PBS -N megahit
#PBS -l nodes=1:ppn=12
#PBS -l mem=50gb
#PBS -l walltime=00:12:00:00
#PBS -q iw-shared-6
#PBS -j oe
#PBS -o $HOME/job_output_files/$PBS_JOBNAME.$PBS_JOBID.txt
#PBS -m abe
#PBS -M waoverholt@gatech.edu

INPUT=/nv/hp10/woverholt3/kostka-dir/Will_testing-metagenome-assemblers/megahit_full_clean/final.contigs.fa
BAM=/nv/hp10/woverholt3/kostka-dir/Will_testing-metagenome-assemblers/megahit_full_clean/bam_files/*.bam
PROCS=`wc -l < ${PBS_NODEFILE}`

echo "started on `/bin/hostname`"
echo
echo "PATH is [$PATH]"
echo
echo "Nodes chosen are:"
cat $PBS_NODEFILE
echo

COMMAND="$HOME/data/program_files/metagenomic_binning/berkeleylab-metabat-cbdca756993e/runMetaBat.sh -t $PROCS $INPUT $BAM"

echo $COMMAND

/usr/bin/time -v $COMMAND

